image: registry.ci.infra.lan:5000/project-1:server-build_QA

stages:
  - QA
  - build
  - deploy

before_script:
  - export GROUP_NUMBER=${CI_PROJECT_NAMESPACE##*-}
  - export STUDENT_SET=$(echo $CI_PROJECT_NAMESPACE | awk -F'/' '{print $6}')
  - echo -e "server.port=$((8100 + 10#$GROUP_NUMBER))\nspec.url=https://project-1.ti.howest.be/2023-2024/labyrinth-api-spec/labyrinth-api-spec.yaml" > server/src/main/resources/config.properties
  - ln -s /home/gradle/.gradle .gradle

testing:
  stage: QA
  rules:
    - if:
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - gradle clean test --info
    - gradle sonarqube
  artifacts:
    when: always
    reports:
      junit: server/build/test-results/test/**/TEST-*.xml

build:
  stage: build
  needs:
    - testing
  rules:
    - if:
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    # Log config: log to file
    - echo -e "handlers=java.util.logging.FileHandler\n.level=INFO\njava.util.logging.FileHandler.pattern=/var/www/html/logs/LabyrinthServer-logs-group-$GROUP_NUMBER-$STUDENT_SET.txt\njava.util.logging.FileHandler.count=1\njava.util.logging.FileHandler.formatter=java.util.logging.SimpleFormatter" > server/src/main/resources/vertx-default-jul-logging.properties
    - gradle shadowJar
  artifacts:
    untracked: false
    paths:
      - server/build/libs/

deployment:
  stage: deploy
  image: registry.ci.infra.lan:5000/project-1:server-deploy
  needs:
    - testing
    - build
  variables:
    year: 2023-2024
  rules:
    - if:
        $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  script:
    - echo "I will do some deployment stuff now"
    - mv server/build/libs/*.jar ${CI_PROJECT_NAMESPACE##*/}.jar
    - rsync -e "ssh" ${CI_PROJECT_NAMESPACE##*/}.jar gitlab-runner@project-1.ci.infra.lan:/opt/${year}/$STUDENT_SET/${CI_PROJECT_NAMESPACE##*/}/server
    - ssh gitlab-runner@project-1.ci.infra.lan sudo systemctl restart ${CI_PROJECT_NAMESPACE##*/}-$STUDENT_SET

